baseURL = "https://aquilax.avtobiografia.com/"
languageCode = "en-us"
title = "Hugo Mastodon"
theme = "mastodon-api"

[taxonomies]
    user = "users"

[outputs]
    users = ["json"]
    page = ["json"]
    section = ["json"]
